# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoApplication' do
  platform :ios, '11.0'
    use_frameworks!
    pod 'MBProgressHUD', '~> 1.2.0'
    pod 'Alamofire'
    pod 'SnapKit', '~> 5.0.0'
    pod 'SimpleKeychain', '~> 0.9'
    pod 'Kingfisher'

  end

